"""Provenance: every file the app ships has a known, original or licensed source.

Fails when a file appears under app/public (copied into the build verbatim)
that is not one of: a registry GLB built by a repo Blender script, a poster
generated by tools/make_signage.py for an artwork id in the dataset, a PDF
generated by this repo and copied by app/scripts/sync-public.mjs, or a
licence text of a shipped dependency. A dropped-in third-party file is the
failure case this guards against.
"""
import json

from conftest import ROOT

PUBLIC = ROOT / "app" / "public"


def _registry():
    reg = json.loads((ROOT / "design" / "asset-registry.json").read_text(encoding="utf-8"))
    return reg["assets"] if isinstance(reg, dict) else reg


def unknown_files(paths):
    world = json.loads((ROOT / "design" / "world.json").read_text(encoding="utf-8"))
    glbs = {a["glb"] for a in _registry()}
    art = {f["artwork"] for f in world["fixtures"] if f.get("artwork")}
    generated_pdfs = {p.name for p in (ROOT / "drawings" / "pdf").glob("*.pdf")} | {"PRD-v0.2.pdf"}
    unknown = []
    for f in paths:
        rel = f.relative_to(ROOT).as_posix()
        name = f.name
        if f.suffix == ".glb":
            ok = rel in glbs
        elif rel.startswith("app/public/assets/signage/"):
            ok = f.stem in art and f.suffix == ".jpg"
        elif rel.startswith("app/public/docs/"):
            ok = name in generated_pdfs or name == "manifest.json"
        elif rel.startswith("app/public/licenses/"):
            ok = name in {"alegreya-sans-OFL.txt", "three-LICENSE.txt"}
        else:
            ok = rel == "app/public/assets/README.md"
        if not ok:
            unknown.append(rel)
    return unknown


def test_every_public_file_has_a_source():
    unknown = unknown_files(sorted(p for p in PUBLIC.rglob("*") if p.is_file()))
    assert not unknown, f"files without a known source: {unknown}"


def test_dropped_in_files_are_flagged():
    fake = [PUBLIC / "assets" / "characters" / "someone-elses.glb", PUBLIC / "assets" / "signage" / "logo.png",
            PUBLIC / "assets" / "signage" / "ART-99.jpg", PUBLIC / "docs" / "vendor.pdf", PUBLIC / "bundle.js"]
    assert len(unknown_files(fake)) == len(fake)


def test_registry_entries_are_original_and_scripted():
    for a in _registry():
        assert a["license"].startswith("original"), a["id"]
        assert "procedural" in a["creator"] or "Claude Code" in a["creator"], a["id"]
        assert (ROOT / a["source"]).exists(), f"{a['id']}: generator {a['source']} missing"
        assert (ROOT / a["glb"]).exists(), a["id"]


def test_public_pdfs_are_byte_copies_of_generated_ones():
    for f in (PUBLIC / "docs").glob("*.pdf"):
        src = ROOT / ("PRD" if f.name.startswith("PRD") else "drawings/pdf") / f.name
        assert src.exists() and src.read_bytes() == f.read_bytes(), f"{f.name} differs from its generated source; run npm run sync"
